// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterDevice(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SetToken(arg1:string):Promise<void>;

export function StartSync():Promise<string>;

export function UploadFile(arg1:string):Promise<void>;
