// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterDevice(arg1) {
  return window['go']['main']['App']['RegisterDevice'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}

export function StartSync() {
  return window['go']['main']['App']['StartSync']();
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
